module.exports = {
  Airlock: require('./Airlock'),
  Approach: require('./Approach'),
  AutomaticDoor: require('./AutomaticDoor'),
  Character: require('./Character'),
  CharacterAI: require('./CharacterAI'),
  Confrontation: require('./Confrontation'),
  DamagePropagation: require('./DamagePropagation'),
  Damageable: require('./Damageable'),
  Door: require('./Door'),
  Element: require('./Element'),
  EncounterManager: require('./EncounterManager'),
  Floor: require('./Floor'),
  Game: require('./Game'),
  Inventory: require('./Inventory'),
  LineOfSight: require('./LineOfSight'),
  Map: require('./Map'),
  Obstacle: require('./Obstacle'),
  PathWalk: require('./PathWalk'),
  PersonalWeapon: require('./PersonalWeapon'),
  Player: require('./Player'),
  Projectile: require('./Projectile'),
  Ressource: require('./Ressource'),
  RessourceType: require('./RessourceType'),
  Ship: require('./Ship'),
  ShipInterior: require('./ShipInterior'),
  ShipWeapon: require('./ShipWeapon'),
  StarSystem: require('./StarSystem'),
  Travel: require('./Travel'),
  View: require('./View'),
  VisionCalculator: require('./VisionCalculator'),
  actions: {
    Action: require('./actions/Action'),
    ActionProvider: require('./actions/ActionProvider'),
    AttackAction: require('./actions/AttackAction'),
    AttackMoveAction: require('./actions/AttackMoveAction'),
    SimpleActionProvider: require('./actions/SimpleActionProvider'),
    TargetAction: require('./actions/TargetAction'),
    TiledActionProvider: require('./actions/TiledActionProvider'),
    TravelAction: require('./actions/TravelAction'),
    WalkAction: require('./actions/WalkAction')
  },
  generators: {
    RoomGenerator: require('./generators/RoomGenerator'),
    StarMapGenerator: require('./generators/StarMapGenerator')
  }
}
